# Generated by Django 4.1 on 2023-06-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_product_prise_orderproduct_product_priсe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_priсe',
            new_name='product_price',
        ),
    ]
